### ISSUE TITLE
Add functionality for setting replayId -2 or -1

### ISSUE THREAD

**Issue by AbKathiriya** [nameko/nameko-salesforce#7]
How to set replyId to -2 to get all the events from past 24 hours?

**Comment by iky** [comment]
Hi, there is no option for setting up `replyId` on start-up and across channels.

An ad hoc solution is to manually set the keys in Redis. Last `replyId` is stored per each subscription and the key is formatted as [``salesforce:replay_id:<channel_name>``](https://github.com/Overseas-Student-Living/nameko-salesforce/blob/master/nameko_salesforce/streaming/client.py#L166). Stop the service, set the key values to `-2` or `-1`, then start the service, it will pick it up and fetch events accordingly.

We also had to do it a few times and I can see having an option (maybe config?) for a blanket ``replyId`` override/reset would be a nice improvement to the library.
